name: Continuous Integration

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1"

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Run `build`
        run: zig build -Doptimize=ReleaseFast

  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Run `fmt`
        run: zig build fmt
